# config summary:
# ! List of all modified PYTHIA 8.223 settings.
jetty_subjets_exe --sj-tasks --pTHatMin=200 --pTHatMax=-1 --jptcut=200 Beams:eCM=5000. --nev=10000 \
BeamRemnants:halfScaleForKT=1 \
BeamRemnants:primordialKThard=2 \
BeamRemnants:primordialKTsoft=0.5 \
Beams:frameType=2 \
ColourReconnection:range=1.5 \
Diffraction:largeMassSuppress=2 \
HadronLevel:Hadronize=off \
HardQCD:all=on \
Init:showChangedParticleData=off \
MultipartonInteractions:alphaSvalue=0.135 \
MultipartonInteractions:ecmPow=0.19 \
MultipartonInteractions:ecmRef=1800 \
MultipartonInteractions:expPow=2 \
MultipartonInteractions:pT0Ref=2.085 \
PartonLevel:MPI=off \
PDF:pSet=8 \
PhaseSpace:bias2SelectionPow=0 \
PhaseSpace:pTHatMin=200 \
Random:seed=2.5 \
Random:setSeed=on \
SigmaProcess:alphaSvalue=0.135 \
SpaceShower:alphaSvalue=0.137 \
SpaceShower:ecmRef=1800 \
StringFlav:etaSup=0.63 \
StringFlav:mesonBvector=3 \
StringFlav:mesonCvector=1.06 \
StringFlav:mesonSvector=0.725 \
StringFlav:mesonUDvector=0.62 \
StringFlav:popcornSpair=0.5 \
StringFlav:probQQ1toQQ0=0.027 \
StringFlav:probQQtoQ=0.09 \
StringFlav:probSQtoQQ=1 \
StringFlav:probStoUD=0.19 \
StringPT:sigma=0.304 \
StringZ:aExtraDiquark=0.5 \
StringZ:aLund=0.3 \
StringZ:bLund=0.8 \
StringZ:rFactB=0.67 \
StringZ:rFactC=1 \
TimeShower:alphaSvalue=0.1383 \
TimeShower:pTmin=0.4 \
TimeShower:pTminChgQ=0.4 \
Tune:ee=3 \
Tune:pp=5
